export interface CountryItem {
  value: string;
  label: string;
  symbol: string;
}

export const ALL_COUNTRIES: CountryItem[] = [
  { value: "Afghanistan", label: "🇦🇫 Afghanistan", symbol: "؋" },
  { value: "Albania", label: "🇦🇱 Albania", symbol: "L" },
  { value: "Algeria", label: "🇩🇿 Algeria", symbol: "د.ج" },
  { value: "Argentina", label: "🇦🇷 Argentina", symbol: "$" },
  { value: "Australia", label: "🇦🇺 Australia", symbol: "A$" },
  { value: "Austria", label: "🇦🇹 Austria", symbol: "€" },
  { value: "Bangladesh", label: "🇧🇩 Bangladesh", symbol: "৳" },
  { value: "Belgium", label: "🇧🇪 Belgium", symbol: "€" },
  { value: "Brazil", label: "🇧🇷 Brazil", symbol: "R$" },
  { value: "Bulgaria", label: "🇧🇬 Bulgaria", symbol: "лв" },
  { value: "Canada", label: "🇨🇦 Canada", symbol: "C$" },
  { value: "Chile", label: "🇨🇱 Chile", symbol: "$" },
  { value: "China", label: "🇨🇳 China", symbol: "¥" },
  { value: "Colombia", label: "🇨🇴 Colombia", symbol: "$" },
  { value: "Croatia", label: "🇭🇷 Croatia", symbol: "€" },
  { value: "Czech Republic", label: "🇨🇿 Czech Republic", symbol: "Kč" },
  { value: "Denmark", label: "🇩🇰 Denmark", symbol: "kr" },
  { value: "Egypt", label: "🇪🇬 Egypt", symbol: "E£" },
  { value: "Estonia", label: "🇪🇪 Estonia", symbol: "€" },
  { value: "Finland", label: "🇫🇮 Finland", symbol: "€" },
  { value: "France", label: "🇫🇷 France", symbol: "€" },
  { value: "Germany", label: "🇩🇪 Germany", symbol: "€" },
  { value: "Greece", label: "🇬🇷 Greece", symbol: "€" },
  { value: "Hong Kong", label: "🇭🇰 Hong Kong", symbol: "HK$" },
  { value: "Hungary", label: "🇭🇺 Hungary", symbol: "Ft" },
  { value: "Iceland", label: "🇮🇸 Iceland", symbol: "kr" },
  { value: "India", label: "🇮🇳 India", symbol: "₹" },
  { value: "Indonesia", label: "🇮🇩 Indonesia", symbol: "Rp" },
  { value: "Ireland", label: "🇮🇪 Ireland", symbol: "€" },
  { value: "Israel", label: "🇮🇱 Israel", symbol: "₪" },
  { value: "Italy", label: "🇮🇹 Italy", symbol: "€" },
  { value: "Japan", label: "🇯🇵 Japan", symbol: "¥" },
  { value: "Kenya", label: "🇰🇪 Kenya", symbol: "KSh" },
  { value: "Malaysia", label: "🇲🇾 Malaysia", symbol: "RM" },
  { value: "Mexico", label: "🇲🇽 Mexico", symbol: "$" },
  { value: "Morocco", label: "🇲🇦 Morocco", symbol: "MAD" },
  { value: "Netherlands", label: "🇳🇱 Netherlands", symbol: "€" },
  { value: "New Zealand", label: "🇳🇿 New Zealand", symbol: "NZ$" },
  { value: "Nigeria", label: "🇳🇬 Nigeria", symbol: "₦" },
  { value: "Norway", label: "🇳🇴 Norway", symbol: "kr" },
  { value: "Pakistan", label: "🇵🇰 Pakistan", symbol: "₨" },
  { value: "Peru", label: "🇵🇪 Peru", symbol: "S/" },
  { value: "Philippines", label: "🇵🇭 Philippines", symbol: "₱" },
  { value: "Poland", label: "🇵🇱 Poland", symbol: "zł" },
  { value: "Portugal", label: "🇵🇹 Portugal", symbol: "€" },
  { value: "Qatar", label: "🇶🇦 Qatar", symbol: "﷼" },
  { value: "Romania", label: "🇷🇴 Romania", symbol: "lei" },
  { value: "Russia", label: "🇷🇺 Russia", symbol: "₽" },
  { value: "Saudi Arabia", label: "🇸🇦 Saudi Arabia", symbol: "﷼" },
  { value: "Serbia", label: "🇷🇸 Serbia", symbol: "Дин." },
  { value: "Singapore", label: "🇸🇬 Singapore", symbol: "S$" },
  { value: "Slovakia", label: "🇸🇰 Slovakia", symbol: "€" },
  { value: "South Africa", label: "🇿🇦 South Africa", symbol: "R" },
  { value: "South Korea", label: "🇰🇷 South Korea", symbol: "₩" },
  { value: "Spain", label: "🇪🇸 Spain", symbol: "€" },
  { value: "Sri Lanka", label: "🇱🇰 Sri Lanka", symbol: "Rs" },
  { value: "Sweden", label: "🇸🇪 Sweden", symbol: "kr" },
  { value: "Switzerland", label: "🇨🇭 Switzerland", symbol: "CHF" },
  { value: "Taiwan", label: "🇹🇼 Taiwan", symbol: "NT$" },
  { value: "Thailand", label: "🇹🇭 Thailand", symbol: "฿" },
  { value: "Turkey", label: "🇹🇷 Turkey", symbol: "₺" },
  { value: "Ukraine", label: "🇺🇦 Ukraine", symbol: "₴" },
  { value: "United Arab Emirates", label: "🇦🇪 UAE", symbol: "د.إ" },
  { value: "United Kingdom", label: "🇬🇧 United Kingdom", symbol: "£" },
  { value: "United States", label: "🇺🇸 United States", symbol: "$" },
  { value: "Vietnam", label: "🇻🇳 Vietnam", symbol: "₫" }
];
