import type { AgentState } from "./api";

export const MOCK_AGENT_STATE: AgentState = {
  plan_id: "demo-plan-ai-2025",
  status: "completed",
  event_config: {
    category: "AI & Neural Networks",
    geography: "San Francisco, USA",
    audience_size: 1500,
    budget_usd: 120000,
    event_dates: "2025-11-12",
    event_name: "Neural Frontiers Summit 2025",
  },
  sponsors: [
    {
      name: "NVIDIA",
      industry: "Hardware / AI Computing",
      geo: "Global",
      tier: "Gold",
      relevance_score: 9.8,
      website: "https://nvidia.com",
    },
    {
      name: "Microsoft Azure",
      industry: "Cloud Infrastructure",
      geo: "Global",
      tier: "Gold",
      relevance_score: 9.5,
      website: "https://azure.microsoft.com",
    },
    {
      name: "Anthropic",
      industry: "AI Research",
      geo: "Global",
      tier: "Silver",
      relevance_score: 9.2,
      website: "https://anthropic.com",
    },
    {
      name: "Weights & Biases",
      industry: "MLOps",
      geo: "USA",
      tier: "Silver",
      relevance_score: 8.7,
      website: "https://wandb.ai",
    },
    {
      name: "Pinecone",
      industry: "Vector Databases",
      geo: "Global",
      tier: "Bronze",
      relevance_score: 8.4,
      website: "https://pinecone.io",
    },
  ],
  speakers: [
    {
      name: "Dr. Jensen Huang",
      bio: "CEO of NVIDIA, pioneer in GPU computing and deep learning infrastructure.",
      topic: "The Future of Accelerated Computing",
      region: "California, USA",
      influence_score: 9.9,
      speaking_experience: 150,
      linkedin_url: "https://linkedin.com/in/jensenhuang",
    },
    {
      name: "Andrej Karpathy",
      bio: "Founding member of OpenAI, former Director of AI at Tesla.",
      topic: "Building Large Language Models from Scratch",
      region: "USA",
      influence_score: 9.7,
      speaking_experience: 45,
      linkedin_url: "https://linkedin.com/in/andrejkarpathy",
    },
    {
      name: "Dr. Fei-Fei Li",
      bio: "Stanford Professor, Co-Director of HAI, creator of ImageNet.",
      topic: "Human-Centered AI and the Future of Vision",
      region: "Stanford, CA",
      influence_score: 9.6,
      speaking_experience: 80,
      linkedin_url: "https://linkedin.com/in/feifeili",
    },
    {
      name: "Sam Altman",
      bio: "CEO of OpenAI, former President of Y Combinator.",
      topic: "The Path to AGI and Beyond",
      region: "USA",
      influence_score: 9.8,
      speaking_experience: 60,
      linkedin_url: "https://linkedin.com/in/samaltman",
    },
  ],
  venues: [
    {
      name: "Moscone Center",
      city: "San Francisco",
      country: "USA",
      capacity: 5000,
      price_range: "$$$ (High)",
      score: 9.5,
      past_events: ["Google I/O", "Dreamforce", "WWDC"],
      source_url: "https://www.moscone.com",
    },
    {
      name: "Oracle Park (Club Level)",
      city: "San Francisco",
      country: "USA",
      capacity: 1200,
      price_range: "$$ (Moderate)",
      score: 8.8,
      past_events: ["TechCrunch Disrupt Reception"],
      source_url: "https://www.mlb.com/giants/ballpark",
    },
  ],
  ticket_tiers: [
    { name: "Early Bird", price: 499, est_sales: 300, revenue: 149700 },
    { name: "General", price: 899, est_sales: 1000, revenue: 899000 },
    { name: "VIP", price: 2499, est_sales: 200, revenue: 499800 },
  ],
  total_est_revenue: 1548500,
  break_even_price: 642,
  schedule: [
    { time: "09:00 AM", topic: "Opening Keynote: The Intelligence Age", speaker: "Sam Altman", room: "Grand Ballroom" },
    { time: "10:30 AM", topic: "GPU Architecture Deep-Dive", speaker: "Jensen Huang", room: "Tech Hall A" },
    { time: "01:00 PM", topic: "Visual Intelligence Seminar", speaker: "Dr. Fei-Fei Li", room: "Room 302" },
    { time: "03:30 PM", topic: "LLM Systems Panel", speaker: "Andrej Karpathy", room: "Grand Ballroom" },
  ],
  exhibitors: [
    { name: "Mistral AI", cluster: "Foundation Models", relevance: 9.4, website: "https://mistral.ai" },
    { name: "Hugging Face", cluster: "Open Source ML", relevance: 9.7, website: "https://huggingface.co" },
    { name: "LangChain", cluster: "AI Orchestration", relevance: 9.1, website: "https://langchain.com" },
  ],
  communities: [
    { name: "SF AI Meetup", platform: "Meetup", size: 25000 },
    { name: "r/MachineLearning", platform: "Reddit", size: 2800000 },
    { name: "AI Alignment Forum", platform: "Direct", size: 12000 },
  ],
  gtm_messages: {
    Twitter: "Neural Frontiers 2025: Join the architects of the future in SF. Keynotes by Sam Altman & Jensen Huang. #NFS2025 #AI",
    LinkedIn: "We are thrilled to announce the Neural Frontiers Summit 2025. A mission-critical gathering of AI researchers and industry leaders. Register now for the Early Bird rate.",
    Discord: "@everyone The Neural Frontiers schedule is LIVE! Check out the sessions with Karpathy and Dr. Li in the #announcements channel.",
  },
  metadata: {
    pricing_analysis: {
      demand_ratio: 1.45,
      base_price: 899,
      historical_pairs_count: 142,
    },
  },
};
